### ISSUE TITLE
StarSpace Models in Shiny App

### ISSUE THREAD

**Issue by lucasfreitas1988** [bnosac/ruimtehol#38]
Is there a problem using the starspace_load_model function in Shiny? My app works locally, but when I deploy it I can't read the models...

**Comment by jwijffels** [comment]
no problems which I'm aware off

**Comment by lucasfreitas1988** [comment]
I saved using method = 'ruimtehol'.

Is there a difference using 'binary' or 'tsv-data.table'?

**Comment by jwijffels** [comment]
yes

**Comment by lucasfreitas1988** [comment]
Which specific type is best for deploy in Shiny? Locally, all three methods work... I saved and loaded with all three methods and locally everything is fine.

**Comment by jwijffels** [comment]
any 3

**Comment by lucasfreitas1988** [comment]
Can saving to .RDa solve it?

**Comment by jwijffels** [comment]
no

**Comment by jwijffels** [comment]
closing as no real indication is given of the error message
