### ISSUE TITLE
Request for sentiment scoring example

### ISSUE THREAD

**Issue by snvv** [bnosac/ruimtehol#43]
Hello
It would be very helpful to provide an example for sentiment scoring.
I have to create a dictionary for sentiment analysis using **txt_sentiment** function.
Thank you

**Comment by jwijffels** [comment]
If you have a supervised dataset with texts with positive/negative connotations, you can build a classification model with this R package and use the embeddings to find similarity of these to being positive/negative.
If you don't have supervised dataset, you can use this R package to build wordvectors and find similarities to a small set of words which are positive/negative to construct your dictionary.
